[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.7"
scraper = "0.20.0"
csv = "1.3.0"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }